<div class="header--main">
  <div class="header--logo">
    <img src="/images/logo.png"/>
  </div>
  <nav class="header--main-menu">
    <ul class="header--main-menu-items">
      <li class="header--main-menu-item">
        <a class="header--main-menu-item-link" href="#">
          <span class="header--main-menu-item-image-channels"></span>
          <span class="header--main-menu-item-text">Kanaler</span>
        </a>
      </li>
      <li class="header--main-menu-item">
        <a class="header--main-menu-item-link" href="#">
          <span class="header--main-menu-item-image-slides"></span>
          <span class="header--main-menu-item-text">Slides</span>
        </a>
      </li>
      <li class="header--main-menu-item">
        <a class="header--main-menu-item-link" href="#">
          <span class="header--main-menu-item-image-screens"></span>
          <span class="header--main-menu-item-text">Skærme</span>
        </a>
      </li>
      <li class="header--main-menu-item">
        <a class="header--main-menu-item-link" href="#">
          <span class="header--main-menu-item-image-templates"></span>
          <span class="header--main-menu-item-text">Templates</span>
        </a>
      </li>
    </ul>
  </nav>
  <div class="header--secondary-menus">
    <div class="header--secondary-menus-inner">
      <div class="header--user-menu">
        <div class="header--user-menu-label">
          <a class="header--user-menu-dropdown-link" href="#">
            <img class="header--user-menu-image" src="/images/user-default.png"/>
            <span class="header--user-menu-name">Profil</span>
          </a>
        </div>
        <nav class="header--user-menu-links">
        </nav>
      </div>
      <div class="header--nav-menu">
        <div class="header--nav-menu-label">
          <a class="header--nav-menu-dropdown-link" href="#">
            <span class="header--nav-menu-label-image"></span>
            <span class="header--nav-menu-label-text">Menu</span>
          </a>
        </div>
        <nav class="header--nav-menu-links">
        </nav>
      </div>
    </div>
  </div>
</div>
