<nav class="nav">
  <a class="nav-toggle-icon">X</a>
  <h2 class="nav--header">Navigation</h2>
  <div class="nav--item-wrapper">
    <a href="#" class="nav--item">Item 1</a>
    <a href="#" class="nav--item">Item 2</a>
  </div>
  <div class="nav--item-wrapper">
    <a href="#" class="nav--item">Item 1</a>
    <a href="#" class="nav--sub-item">Sub item</a>
    <a href="#" class="nav--item">Item 2</a>
    <a href="#" class="nav--item">Item 3</a>
  </div>
</nav>