application:
    environment:
        php:
            version: 5.5.14
        timezone: 'Europe/Copenhagen'

tools:
    external_code_coverage: false
    php_analyzer: true
    php_cpd: false
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_sim: true
    sensiolabs_security_checker: true

    js_hint:
        use_native_config: false
        config:
            laxcomma: true
            node: true
            browser: true
            esnext: true
            bitwise: true
            camelcase: true
            curly: true
            eqeqeq: true
            immed: true
            indent: 2
            latedef: true
            newcap: true
            noarg: true
            quotmark: true
            undef: true
            unused: true
            strict: true
            trailing: true
            shadow: true
            smarttabs: true
            multistr: true
            globals:
                jasmine: true
                angular: true
                browser: true
                element: true
                app: false
                $: false

filter:
    excluded_paths:
        - 'app/*'
        - 'web/assets/libs/*'

checks:
    php:
        variable_existence: true
        uppercase_constants: true
        uppercase_basic_constants: true
        unused_variables: true
        unreachable_code: true
        symfony_request_injection: true
        switch_fallthrough_commented: true
        sql_injection_vulnerabilities: true
        unused_methods: true
        no_unnecessary_if: true
        no_empty_statements: true
        spacing_of_function_arguments: true
        spacing_around_non_conditional_operators: true
        spacing_around_conditional_operators: true
        space_after_cast: true
        simplify_boolean_return: true
        scope_indentation:
            spaces_per_level: '2'
        require_scope_for_properties: true
        require_braces_around_control_structures: true
        properties_in_camelcaps: true
        prefer_unix_line_ending: true
        php5_style_constructor: true
        parameters_in_camelcaps: true
        optional_parameters_at_the_end: true
        non_commented_empty_catch_block: true
        no_trailing_whitespace: true
        no_space_inside_cast_operator: true
        no_space_before_semicolon: true
        no_short_open_tag: true
        no_goto: true
        no_global_keyword: true
        no_error_suppression: true
        no_commented_out_code: true
        lowercase_php_keywords: true
        function_body_start_on_same_line: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        blank_line_after_namespace_declaration: true
        avoid_todo_comments: true
        avoid_tab_indentation: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_length_functions_in_loops: true
        avoid_fixme_comments: true
        avoid_closing_tag: true
        avoid_aliased_php_functions: true
        duplication: true
        no_eval: true
        return_doc_comments: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        avoid_unnecessary_concatenation: true
        deprecated_code_usage: true
        no_debug_code: true
        code_rating: true
        verify_access_scope_valid: true
        useless_calls: true
        use_statement_alias_conflict: true
        use_self_instead_of_fqcn: true
        unused_properties: true
        unused_parameters: true
        single_namespace_per_use: true
        side_effects_or_types: true
        security_vulnerabilities: true
        return_doc_comment_if_not_inferrable: true
        require_scope_for_methods: true
        require_php_tag_first: true
        remove_trailing_whitespace: true
        prefer_while_loop_over_for_loop: true
        precedence_mistakes: true
        precedence_in_conditions: true
        parameter_non_unique: true
        overriding_private_members: true
        one_class_per_file: true
        no_unnecessary_function_call_in_for_loop: true
        no_non_implemented_abstract_methods: true
        no_property_on_interface: true
        no_mixed_inline_html: true
        no_exit: true
        no_duplicate_arguments: true
        newline_at_end_of_file: true
        missing_arguments: true
        instanceof_class_exists: true
        function_in_camel_caps: true
        fix_php_opening_tag: true
        fix_linefeed: true
        deadlock_detection_in_loops: true
        catch_class_exists: true
        avoid_usage_of_logical_operators: true
        avoid_entity_manager_injection: true
        assignment_of_null_return: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: false
                size: 2
            switch:
                indent_case: true
        spaces:
            before_parentheses:
                function_declaration: false
                closure_definition: true
                function_call: false
                if: true
                for: true
                while: true
                switch: true
                catch: true
                array_initializer: false
            around_operators:
                assignment: true
                logical: true
                equality: true
                relational: true
                bitwise: true
                additive: true
                multiplicative: true
                shift: true
                unary_additive: false
                concatenation: true
                negation: false
            before_left_brace:
                class: true
                function: true
                if: true
                else: true
                for: true
                while: true
                do: true
                switch: true
                try: true
                catch: true
                finally: true
            before_keywords:
                else: true
                while: true
                catch: true
                finally: true
            within:
                brackets: false
                array_initializer: false
                grouping: false
                function_call: false
                function_declaration: false
                if: false
                for: false
                while: false
                switch: false
                catch: false
                type_cast: false
            ternary_operator:
                before_condition: true
                after_condition: true
                before_alternative: true
                after_alternative: true
                in_short_version: true
            other:
                before_comma: false
                after_comma: true
                before_semicolon: false
                after_semicolon: true
                after_type_cast: true
        braces:
            classes_functions:
                class: end-of-line
                function: end-of-line
                closure: end-of-line
            if:
                opening: end-of-line
                always: true
                else_on_new_line: true
            for:
                opening: end-of-line
                always: true
            while:
                opening: end-of-line
                always: true
            do_while:
                opening: end-of-line
                always: true
                while_on_new_line: false
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
                catch_on_new_line: true
                finally_on_new_line: true
