<div class="header--sub">
  <div class="header--sub-inner">
    <nav class="header--sub-menu">
      <ul class="header--sub-menu-items">
        <li class="header--sub-menu-item">
          <a class="header--sub-menu-item-link" href="#">
            <span class="header--sub-menu-item-image-overview"></span>
            <span class="header--sub-menu-item-text">Oversigt</span>
          </a>
        </li>
        <li class="header--sub-menu-item">
          <a class="is-active header--sub-menu-item-link" href="#">
            <span class="header--sub-menu-item-image-create-channel"></span>
            <span class="header--sub-menu-item-text">Opret kanal</span>
          </a>
        </li>
      </ul>
    </nav>
  </div>
</div>